all: Main Food Restaurant Customer Order
	g++ main.o food.o restaurant.o customer.o order.o
	./a.out
Main:
	g++ -c main.cpp
Food:
	g++ -c food.cpp
Restaurant:
	g++ -c restaurant.cpp
Order:
	g++ -c order.cpp
Customer:
	g++ -c customer.cpp
